######################## default configuration ####################
baseURL = "https://www.kochessenz.de/"
title = "kochessenz"
theme = "galaxy-hugo"
# post pagination
paginate = "10"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
defaultContentLanguage = "de"
disableLanguages = [] 

############################# output ##############################
[outputs]
home = ["HTML", "RSS", "JSON"]


# unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
scripttype= "text/javascript"
cookieconsent = "strictly-required"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
scripttype= "text/plain"
cookieconsent = "functionality"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
scripttype= "text/plain"
cookieconsent = "functionality"
[[params.plugins.js]]
link = "plugins/search/mark.js"
scripttype= "text/plain"
cookieconsent = "functionality"
[[params.plugins.js]]
link = "plugins/search/search.js"
scripttype= "text/plain"
cookieconsent = "functionality"
