############# German navigation ##############

# main menu
[[main]]
name = "Home"
URL = "/"
weight = 1

[[main]]
name = "Über kochessenz"
URL = "about/"
weight = 2

[[main]]
name = "Rezepte"
URL = "post/"
weight = 4
  
[[main]]
name = "Zutaten"
URL = "tags/"
weight = 5
  
[[main]]
name = "Kontakt"
URL = "contact/"
weight = 6

[[main]]
name = "Impressum/Datenschutz"
URL = "privacy-policy/"
weight = 7
