############# English navigation ##############

# main menu
[[main]]
name = "Home"
URL = "en/"
weight = 1

[[main]]
name = "About kochessenz"
URL = "en/about/"
weight = 2

[[main]]
name = "Recipes"
URL = "en/post/"
weight = 4
  
  
[[main]]
name = "Ingredients"
URL = "en/tags/"
weight = 5
  
[[main]]
name = "Contact"
URL = "en/contact/"
weight = 6

[[main]]
name = "Imprint/Privacy"
URL = "en/privacy-policy/"
weight = 7



