[params]
logo = "images/logo.png"
# Meta data
description = "kochessenz Food Blog"
author = "Martin Jahr"
# contact info
address = "26603 Aurich"
mobile = "+49 151 5989 1333"
email = "info@kochessenz.de"
# contact form action
contact_form_action = "https://formspree.io/f/xgebvebp"
# Google Analitycs
google_analitycs_id = "" # your id
# search
search = false

# Preloader
[params.preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
#mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
#mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

  
############################# social site ########################
[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/martin-jahr-72559214b/"


